### ISSUE TITLE
This plugin is immaculate!

### ISSUE THREAD

**Issue by linc** [R-J/PrefixDiscussion#1]
A client requested this be added for them on cloud. I frequently cringe at code reviews like that, but this plugin is spotless. Well done. 😊

**Comment by R-J** [comment]
Thanks, I really feel flattered! :smiley:

**Comment by kaecyra** [comment]
We no longer put `defined('APPLICATION') or die;` at the beginning of class definition files, but otherwise I agree. Very good looking code.

**Comment by R-J** [comment]
I have reworked it and will check it against your coding standards tomorrow. Afterwards I'll update this repo with an optimized version! :-))
